config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  devise_for :users, controllers: { registrations: "users/registrations" }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  root 'tasks#index'
  
  get '/complete/:id', to: 'tasks#complete', as: 'complete'
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  validates :name, presence: true
  validates :description, presence: true
  default_scope -> { order(updated_at: :desc) }

  scope :complete, -> { where(complete: true) }
  scope :incomplete, -> { where(complete: nil) }

  def count
  	count
  end

  def mark_complete!
  	self.update_attribute(:complete, true)
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :tasks, dependent: :destroy
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  def soft_user?
  	self.email.empty?
  end
  
  def needs_engagement?
    tasks = Task.where(soft_token: self.soft_token)
      if self.soft_user? && tasks.count >= 2
      true
    end
  end       
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  def authenticate_user!(*args)
    current_user.present? || super(*args)
  end

  def current_user
   super || User.where(soft_token: soft_token).first_or_initialize
  end

  private

	def soft_token
	  session[:user_token] ||= SecureRandom.hex(8)
	end
	
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:edit, :update, :destroy]

  respond_to :html, :js

  def index
    @user = current_user
    if @user.soft_user?
      @tasks = Task.where(soft_token: @user.soft_token)
    else
      @tasks = @user.tasks.all
    end
    respond_with(@tasks)
  end

  def new
    @task = Task.new
    respond_with(@task)
  end

  def edit
  end

  def create
    @user = current_user
    @task = Task.new(task_params)

    if @user.soft_user?
      @task.soft_token = @user.soft_token
    end

    if @task.save
      flash[:success] = "Your task was created successfully!"
      respond_with(@task)

    else
      flash[:warning] = "Your task could not be created!"
      render 'edit'
    end
  end

  def update
    @task.update(task_params)
    flash[:notice] = "Your task was updated successfully!"
    respond_with(@task)
  end

  def destroy
    @task.destroy
    flash[:warning] = "Your task was deleted successfully!"
    respond_with(@task)
  end

  def count 
    @tasks.count
  end

  def complete
    @task = Task.find(params[:id])
    flash[:alert] = "Congrats on completing another task!"
    @task.mark_complete!
  end

  private
    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:name, :description, :completed, :user_id)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
    def configure_sign_up_params
      devise_parameter_sanitizer.for(:sign_up) << :soft_token
    end

    def merge_tasks
      tasks = Task.where(soft_token: current_user.soft_token)
      tasks.map do |task|
        task.user = current_user
        task.user_id = current_user.id
        task.save!
      end
    end

    #The path used after sign up.
    def after_sign_up_path_for(resource)
      merge_tasks
      super(resource)
      root_path
    end

    def after_sign_out_path_for(resource)
      flash[:notice] = "You have successfully signed out"
      super(resource)
    end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
      { 
        success: "alert-success", 
        error: "alert-danger", 
        alert: "alert-warning", 
        notice: "alert-info" 
      }
      [flash_type] || flash_type.to_sym
  end

  def flash_messages(opts = {})
    flash.each do |flash_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(flash_type)} fade in") do 
              concat content_tag(:button, 'X'.html_safe, class: "close", data: { dismiss: 'alert' })
              concat message 
            end)

    end
    nil
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/_alerts.html.erb
<% unless flash.blank? %>
   <% flash.each do |type, message| %>
      <div class="alert alert-<%= bootstrap_class_for(type) %> fade in">
        <button class="close" data-dismiss="alert">X</button>
        <%= message %>
      </div>
   <% end %>
<% end %>

app/views/layouts/_dashboard.html.erb
<div id="dash_container" class="panel panel-default">
  <div class="row">
    <div id="box1" class="col-md-3 col-sm-12 col-xs-3 box well">
        <% if current_user.soft_user? %>
            <div class="task_digit"><%= Task.where(soft_token: @user.soft_token).count %></div>
            <div class="task_text"><%= "Task".pluralize(Task.where(soft_token: @user.soft_token).count) %> <br> Created</div>
        <% else %>
            <div class="task_digit"><%= current_user.tasks.count %></div>
            <div class="task_text"><%= "Task".pluralize(Task.all.count) %> <br> Created</div>
        <% end %>
    </div>
    <div id="box2" class="col-md-3 col-sm-12 col-xs-3 box well">
        <div class="task_digit"><%= current_user.tasks.complete.count %></div>
        <div class="task_text"><%= "Task".pluralize(Task.complete.count) %> <br> Completed</div>
    </div>
    <div id="box3" class="col-md-3 col-sm-12 col-xs-3 box well">
        <div class="task_digit"><%= current_user.tasks.incomplete.count %></div>
        <div class="task_text"><%= "Task".pluralize(Task.incomplete.count) %> <br> Incomplete</div>
    </div>
  </div>
</div><!--items-container-->

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
    <div class="alert alert-danger fade in" id="error_explanation">
      <h4><strong>Couldn't save task!</strong> Please correct the following errors:</h4>
      <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
<% end %>

app/views/layouts/_navigation.html.erb
  <div class="container-fluid">
    <div class="navbar-header">
      <span class="navbar-brand" href="#">Task Manager</span>
    </div>
    <div>
      <ul class="nav navbar-nav">
        <li><a href="#"></a></li>
        <li><a href="#"></a></li>
        <li><%= link_to 'New Task', new_task_path, remote: true, id: "new-task", class: "btn-md btn-success" %></li> 
      </ul>
      <ul class="nav navbar-nav navbar-right">

      <% if current_user.soft_user? %>
        <li>
          <%= link_to new_user_registration_path do %>
            <span class="glyphicon glyphicon-user"></span>
            Sign Up
          <% end %>
        </li>
        <li>
          <%= link_to new_user_session_path do %>
            <span class="glyphicon glyphicon-log-in"></span>
            Sign In
          <% end %>
        </li>
      <% else %>
        <li>
          <%= link_to destroy_user_session_path remote: true do %>
            <span class="glyphicon glyphicon-chevron-left"></span>
            Sign Out
          <% end %>
        </li>
        <li>
          <%= link_to edit_user_registration_path do %>
            <span class="glyphicon glyphicon-edit"></span>
            Edit Profile
          <% end %>
        </li>
      <% end %>
      </ul>
    </div>
  </div>

app/views/layouts/_overlay.html.erb
<div class="navbar navbar-default nav-close">
	<div class="col-md-12 pull-right" id="close">
	   <span class="line" id="line1"></span>
	   <span class="line" id="line2"></span>
	</div>
</div>
<div class="container">	
  <div class="row">
	<div class="col-md-6 form-container">
        
	</div>
  </div>
</div>

app/views/layouts/_sign_up_alert.html.erb
<div class="alert must-register" role="alert">
    You must <strong><%= link_to "Sign Up", new_user_registration_path, class: "alert-link" %></strong> to continue creating tasks.
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Taskmanager</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<div class="flash">
  <%= render partial: 'layouts/alerts' %>
</div>

<body>

  <%= yield %>

<br>

	<div>   
	   <%= current_user.inspect %>
	</div>   
</body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task, :html => {:class => "new_task"}, remote: true) do |f| %>

<%= render 'layouts/error', obj: @task %>

  <div class="form-group">
    <%= f.label :task_Name, class: 'control-label', id: 'name-label' %><br>
    <%= f.text_field :name, placeholder: "Task Name", class: 'form-control input-lg' %>
  </div>
  <div class="form-group">
    <%= f.label :description, class: 'control-label', id: 'description-label' %><br>
    <%= f.text_area :description, placeholder: "Description", class: 'form-control input-lg' %>
  </div>
  <div class="form-group">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="form-group">
     <%= f.submit class: 'col-md-8 col-sm-6 btn btn-primary form-btn', id: 'task-submit-btn' %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<%= div_for task do %>
    <div class="container-fluid">
	    <div class="row">
			<h4 class="task_name"><%= task.name %>
	          <%= link_to edit_task_path(task), remote: true do %>
				 <span class="glyphicon glyphicon-pencil"></span>
			  <% end %>
			  <%= link_to complete_path(task), remote: true do %>
				 <span class="glyphicon glyphicon-ok"></span>
			  <% end %>
			  <%= link_to task, remote: true, method: :delete do %>
				 <span class="glyphicon glyphicon-remove"></span>
			  <% end %>
		    </h4>
		</div>
		<h5 class="task_desc"><%= task.description %></h5>
	</div>
<% end %>

app/views/tasks/complete.js.erb
$('div#<%= dom_id(@task) %>').fadeOut();
$('#complete_tasks').prepend('<%= j render partial: "tasks/task", locals: {task: @task} %>');
$('.task-numbers').html('<%= j render "layouts/dashboard" %>');

app/views/tasks/create.js.erb
  $('.overlay').css({ opacity: '0', visibility: 'hidden' })
  $('.task-numbers').html('<%= j render "layouts/dashboard" %>')
  $('#incomplete_tasks').prepend('<%= j render partial: "task", locals: {task: @task} %>');

app/views/tasks/destroy.js.erb
$('div#<%= dom_id(@task) %>').fadeOut();
$('.task-numbers').html('<%= j render "layouts/dashboard" %>');

app/views/tasks/edit.js.erb
$('.form-container').html("<%= j (render 'form') %>")
$('.overlay').css({ opacity: '1', visibility: 'visible' });

app/views/tasks/index.html.erb
<div class="overlay">
    <%= render 'layouts/overlay' %>
</div>

<nav class="navbar navbar-default">
    <%= render 'layouts/navigation' %>
</nav>

<div class="container task-numbers">
	<%= render 'layouts/dashboard' %>
</div>

<div id="task_container" class="container-fluid">


  <h3 class="task_title">Incomplete Tasks</h3>
    <% if @tasks.empty? %>
        <h4> You haven't created any tasks yet get started by clicking the "new task" button above. </h4>
    <% else %>
		<div class="my_tasks" id="incomplete_tasks">
		  <% @tasks.incomplete.each do |task| %>
		    <%= render task %>
		  <% end %>
		</div>
    <% end %>

  <div id="divider"></div>

  <h3 class="task_title">Completed Tasks</h3>
	<div class="my_tasks" id="complete_tasks">
	  <% @tasks.complete.each do |task| %>
	    <h4><%= task.name %></h4>
	    <h5><%= task.description %></h5>
	  <% end %>
	</div>

</div>

app/views/tasks/new.html.erb
<% if current_user.needs_engagement? %>
<%= link_to 'You Must Register!', new_user_registration_path %>
  <% else %>
  <% render 'form' %>
<% end %>

app/views/tasks/new.js.erb
<% if current_user.needs_engagement? %>
  $(".flash").html("<%= j (render 'layouts/sign_up_alert') %>")
<% else %>
  $('.form-container').html("<%= j (render 'form') %>")
  $('#new-task').bind('click', function() {
	$('.overlay').css({ opacity: "1", visibility: "visible" })
  })
<% end %>

app/views/tasks/show.html.erb
<p>
  <strong>Name:</strong>
  
</p>

<p>
  <strong>Description:</strong>
  
</p>

<%= link_to 'Back', task_path %>

app/views/tasks/update.js.erb
$('.overlay').css({ opacity: '0', visibility: 'hidden' });
$('div#<%= dom_id(@task) %>').replaceWith('<%= j render partial: "task", locals: {task: @task} %>');